### ISSUE TITLE
cityscapes model

### ISSUE THREAD

**Issue by vobecant** [rstrudel/segmenter#21]
Dear authors,

can you please share the weights of the model trained on the Cityscapes dataset?

Thank you very much in advance.

Best,
Antonin.

**Comment by rstrudel** [comment]
Hi @vobecant ,
We uploaded the weights of the model on Cityscapes, please check it out!
Robin

**Comment by vobecant** [comment]
Thanks @rstrudel !

**Comment by vobecant** [comment]
Dear @rstrudel ,
I see that the model is `Seg-L-Mask/16`. As I recall, in one of your earlier paper versions, you said that you were not able to train larger models than `Seg-B†-Mask/16`. Can I please ask you how did you manage to train the `Large` variant? I tried to fit something to V100 but I was not able to train the Large model.
Also, I see in the `variant.yml` that you don't even use `amp`.
Thank you very much in advance!

**Comment by rstrudel** [comment]
Hi @vobecant,
Sure, as specified in the paper for Cityscapes we train the mask transformer with 1 layer instead of two and it does fit memory on 8 V100 GPUs with 32Go of memory. We indeed added amp in the settings to speed up training. Unfortunately it made training really unstable and prone to NaN values after a while in some cases. Thus we just decided to turn it off and opt for the slower but more reliable full numerical precision.
