### ISSUE TITLE
how to get the attention maps

### ISSUE THREAD

**Issue by sijiua** [rstrudel/segmenter#39]
first the folder named images don’t have the file named im0.jpg.
![image](https://user-images.githubusercontent.com/89134118/156720938-50023a5b-0fa4-4310-8fdd-412ca220c2c3.png)
![image](https://user-images.githubusercontent.com/89134118/156721010-acc7610f-e5da-49a7-b7c8-4c16caf42731.png)
they release the message  
![image](https://user-images.githubusercontent.com/89134118/156721093-f9d606ed-0981-411c-99a6-e0f53f27567e.png)
if i replace the folder images/validation/ADE_val_0000000.jpg
ValueError: Provided image path images/training/ADE_train_00016528 is not a valid image file.

and what is the output_dir
![image](https://user-images.githubusercontent.com/89134118/156721498-d3a75b4b-71e8-4531-9cb5-d8b1caccc8f9.png)

**Comment by rgpinel** [comment]
Hi @sijiua,

The command given in `README.md`:

```
python -m segm.scripts.show_attn_map seg_tiny_mask/checkpoint.pth \
images/im0.jpg output_dir/ --layer-id 0 --dec --cls
```

is just an example of how to use the script. 

You need to replace:

- `seg_tiny_mask/checkpoint.pth` with the path where you store the model checkpoint.
-  `images/im0.jpg` with the path of the image that you want to use as an input of the model.
- `output_dir/` with the path of the directory where you want to store the output attention map images.

In you image above, it seems that you get the `Error: Missing argument 'OUTPUT_DIR'` because you are only providing two arguments instead of the three required (the three described above).

**Comment by sijiua** [comment]
I will try it

**Comment by sijiua** [comment]
![image](https://user-images.githubusercontent.com/89134118/156880915-6b4acb61-ab79-4c7a-816e-c941a984f123.png)
ALWAYS REMIND ME THIS FAULT,EVEN I PUT THE ABSOLUTE PATH

**Comment by rgpinel** [comment]
Please, could you send the complete command you are using to run the script?

Are you sure the path you are using for the image is correct? Can you `ls` the same image path you are giving as an input to the command?

I have ran the following command on my side (with the same image from ADE20K):
``` python -m segm.scripts.show_attn_map ./models/segm/checkpoint.pth $DATASET/ade20k/ADEChallengeData2016/images/validation/ADE_val_00000321.jpg output_dir/ --layer-id 0 --dec --cls ```
and it works well.

**Comment by sijiua** [comment]
thank u,it works.

**Comment by sijiua** [comment]
maybe you can put this command into README.md
