### ISSUE TITLE
Make a PR to MMSegmentation

### ISSUE THREAD

**Issue by Junjun2016** [rstrudel/segmenter#4]
Great work!
Could you please make a PR to [MMSegmentation](https://github.com/open-mmlab/mmsegmentation)?

**Comment by MengzhangLI** [comment]
Hi, Robin.

It is absolutely a great work, we are members of OpenMMLab, right now we are working to merge many transformer models into our official OpenMMLab codebase. If your time available, could you create a new PR about segmenter to MMSegmentation thus we could work together for this great model, and we could provide it for many researchers around the world.

I guess it won't take too much time because it is based on MMSegmentation.

Feel free to contact us anytime. Wish you a good day.

Best,

**Comment by rstrudel** [comment]
Hi,

Thanks for the suggestion, I do think it's a good idea I will start to work on it and propose a PR. It might take some time to make sure details and performances match otherwise this sounds good.

Robin

**Comment by MengzhangLI** [comment]
> Hi,
> 
> Thanks for the suggestion, I do think it's a good idea I will start to work on it and propose a PR. It might take some time to make sure details and performances match otherwise this sounds good.
> 
> Robin

OK, Robin. No problem!

Let's work together to enable many other researchers and students could use this model on MMSegmentation.

Have a good day.

Best,

**Comment by rstrudel** [comment]
Cf https://github.com/open-mmlab/mmsegmentation/pull/955 .
